name=UltraSense
version=2.0.0
author=OneDevelopment & OpenLibraries-Arduino
maintainer=OneDevelopmentPL
sentence=Simple ultrasonic sensor library for HC-SR04.
paragraph=Lightweight and easy to use ultrasonic sensor library with filtering, montion etc.
category=Sensors
url=https://github.com/OneDevelopmentPL/UltraSense
architectures=*

